services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "3002:3002"
      - "5321:5321"
    restart: always
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    network_mode: "host"

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
      # - "5321:5321"
      - "85:85"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt:ro
    depends_on:
      - app
    restart: always
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    network_mode: "host"
   
